<?php
$page_info['section'] = 'news';
$page_info['page'] = 'article';
$page_info['login_required'] = 0;
list($user_info, $lang, $status_message, $header) = vlc_header($site_info, $page_info);
print $header;
?>
<!-- begin page content -->
<p class="center"><b>Media Literacy in Cyberspace (Part I)</b></p>
<p class="center">By Antonio D. Sison</p>
<p><i>Antonio David Sison is a Filipino theologian who works in the interdisciplinary area of Theology and Cinema. His doctoral research was on the confluence of Edward Schillebeeckx's Eschatology and Third Cinema. He is also a screenwriter and independent filmmaker. He is currently in the initial formation program of the Missionaries of the Precious Blood in Dayton, Ohio. His e-mail is <?php print vlc_mailto_link('ton_sison@yahoo.com', 'ton_sison@yahoo.com', 'VLCFF') ?>.</i></p>
<p>Boston-based Joanne Pratt, a grandmother of five, is all fired up. She is part of a virtual learning community for an online course on media literacy. Media literacy essentially means acquiring a keen awareness of our media environment and developing skills that enable one to get into a critical engagement with media culture.</p>
<p>The course requires her to do critical readings, theological reflections on media products, and to &quot;show up&quot; and participate consistently in a couple of online discussion boards at any hour of the day but within an ordered timeline of five weeks.</p>
<p>The fostering of a virtual learning community, which involves journeying towards media literacy with other participants, distinguishes the online course from the usual teacher-student correspondence courses.</p>
<p>A product of the old school of learning where almost everything was learned by rote, Joanne recognizes that the online course represents a steep learning curve. But she is undaunted. Having been in religious education for almost 30 years, she has an astute perception of media literacy. &quot;I need to be media-savvy to be more effective in my work,&quot; she said. About the overwhelming tide of information in cyberspace, she said, &quot;Avoid it we cannot. So, let's name it, let's study it, let's make it our friend. Jesus used parables, I'll bet he'd use the Internet today.&quot;</p>
<p>As a facilitator of a virtual learning course titled Media, Faith, and Values, I too have to negotiate through a learning curve. Having been confined in the ivory tower of graduate school theology in Europe, I am learning the dynamics of a new, humbler pedagogy, that means learning to be a listener, indeed, learning to be a co-learner. This is precisely the spirit behind the course, to be a community of learners sharing the common grammar of conversation and dialogue.</p>
<p>Media, Faith, and Values is one of the courses under the Virtual Learning Community of Faith Formation pioneered by the University of Dayton's Institute for Pastoral Initiatives in the year 2000. A program supported by the Marianist province of the United States and the University of Dayton the Virtual Learning Community aims at making adult education accessible to catechists, Catholic educators and ordinary adults who want to learn more about their faith, but are encumbered by a busy schedule or who are geographically distant from traditional seats of learning. This year a thousand students, the programs highest enrollment, registered to join virtual learning communities from locations as diverse as Wichita, Kansas, and Manila, Philippines.</p>
<p>Promoting media literacy is so important, perhaps now more than ever. Educators and parents everywhere are at wit's end in the face of media omnipresence and the breakneck speed of cyber technology. Studies show that young people are weaned on at least 7-8 hours of television a day. And who's to say about the hours they spend surfing the Internet.</p>
<p>Sr. Rose Pacatte, a virtual learning community facilitator and director of the Pauline Center for Media Studies in Los Angeles, notes that media literacy equips adults with dialogue tools so they can talk with kids about their media exposure. &quot;A lot of parents will stop being afraid of the media world if they're more aware of their own media world and their own practices and values,&quot; she said. &quot;Then they will have some control over it, because they can say why they don't like something and why it's inappropriate for the child.&quot;</p>
<p>I couldn't agree more. In my experience as course facilitator for Media, Faith and Values, I observed that most participants start with a lot of media bashing: We must get our kids off the TV. This show has a lot of foul language. We must join forces to boycott this film. But by week five of the course, there is a noticeable change in tone on the discussion boards; a more self-assured openness to ventilate issues and to get into a dialogue about media emerges.</p>
<p>Participants begin to realize that no matter how frantic their efforts are at playing media police, kids will seek out media anyway. As such, there is wisdom in understanding the language of media and getting immersed in media culture with kids; to create a safe space for a conversation.</p>
<p>Conversation, or call it critical dialogue, is the aim of media literacy, a conversation about media and with media.</p>
<p>Aetatis Novae (Dawn of a New Era), the pastoral instruction on social communications, reverberates with the call of Communio et Progressio for the &quot;teaching church&quot; to strive also to be a &quot;listening church.&quot; It takes a proactive, dialogical stance towards media culture:</p>
<blockquote>Thus, in seeking to enter into dialogue with the modern world, the church necessarily desires honest and respectful dialogue with those responsible for the communications media. On the church's side this dialogue involves efforts to understand the media -- their purposes, procedures, forms and genres, internal structures and modalities -- and to offer support and encouragement to those involved in media work.</blockquote>
<p>At the helm of the Virtual Learning Community of Faith Formation is Sr. Angela Ann Zukowski, a Mission Helpers of the Sacred Heart, and one of the driving forces behind Aetatis Novae. A visionary with an indefatigable spirit, Sr. Angela Ann understands that a dialogical approach could mean having to undergo a paradigm shift in catechesis. She is well aware that for many catechists, teachers, or even parents, it will not be an easy move. All of us do suffer from &quot;paradigm myopia&quot; at some level. But she is confident about the power of the next step: &quot;It is a cinch by the inch and hard by the yard.&quot;</p>
<p>Meantime, the critical dialogue is ongoing in cyberspace.</p>
<p class="center"><i>National Catholic Reporter: Global Perspective</i><br><?php print vlc_external_link('http://www.nationalcatholicreporter.org/globalpers/gp091604.htm', 'http://www.nationalcatholicreporter.org/globalpers/gp091604.htm') ?><br>September 16, 2004</p>
<!-- end page content -->
<?php
$footer = vlc_footer($site_info, $page_info, $user_info, $lang);
print $footer;
?>

