<?php
$page_info['section'] = 'news';
$page_info['page'] = 'article';
$page_info['login_required'] = 0;
list($user_info, $lang, $status_message, $header) = vlc_header($site_info, $page_info);
print $header;
?>
<!-- begin page content -->
<p class="center"><b>Kaleidoscopic Catechesis: Media Literacy in Cyberspace (Part II)</b></p>
<p class="center">By Antonio D. Sison</p>
<p><i>Sr. Angela Ann Zukowski is the director of the University of Dayton's Institute for Pastoral Initiatives and the Virtual Learning Community of Faith Formation. Her commitment to media literacy is rooted in a continuum of significant catechetical involvements spanning nearly three decades, among them, pioneering work in the use of cable TV for evangelization, sitting as president of the International Catholic Association for Radio and Television, and contributing to the conceptualization and writing of the pastoral document on social communications, Aetatis Novae. Her most recent book is <?php print vlc_external_link('The Gospel in Cyberspace', 'http://www.loyolabooks.org/store/title.asp?isbn=0829417400') ?> with Pierre Babin (Loyola Press).</i></p>
<p><b>Global Perspective: How did you get involved with Aetatis Novae?</b></p>
<p><b>Sr. Angela Ann Zukowski:</b> Some people may say I was at the right place at the right time. However, by 1988 I had a strong history of writing and producing for cable TV and video teleconferences with the NCEA for the Catholic Telecommunications Network of America. Furthermore, I was a member of the [U.S. bishops'] committee on communications and the president of UNDA (now known as the Catholic Academy of the Arts) in the United States. The Vatican's Pontifical Council for Social Communication, whose President is Archbishop John P. Foley, had produced a document which gathered who is doing what and how in Catholic communications around the world. Grounded on this research, 12 or 14 persons were identified from around the world to critically reflect and dialogue not only on what the church is doing but what the church could or should do for advancing the recommendations and insights expressed in Communio et Progressio. The church was coming up to the 20th anniversary of Communio et Progressio, which is seen as the magna carta document of church communication documents, and the pontifical council wanted to take it a step further. The people who were around that table in Nemi, Italy, representing almost every continent, were engaged in a dynamic pastoral dialogue exploring creative options for the church.</p>
<p>Part of that original dreaming about Aetatis Novae was the thought of coming up with something different, a very positive document, not a document that would be negative about media culture, which documents tend to do, but look at something that was more positive, proactive and pastoral. It had to be something that would look at communications as not being independent of other ministries but like a tapestry consciously woven into the very fabric of every ministry activity of the church. This was a wonderful opportunity to take the gospel to the mountaintop, not place it under a basket. Those gathered in Nemi pastorally understood the vast opportunities of a new communication era about to dawn. There was no doubt in their minds that peoples, countries and nations would be linked in new ways. The church would need to understand, embrace and educate her people for this new era in a substantive and institutional manner. In light of this fact, the original gathering had a solid recommendation that every episcopal conference, every diocese, and parish should have an integrative pastoral communications plan. As a matter of fact, the second part of Aetatis Novae offered pastoral guidelines to this effect.</p>
<p><b>What stands out in the document seems to be the call for &quot;an honest and respectful dialogue&quot; with media.</b></p>
<p>I'm glad to hear you point that out. I remember the animated, in-depth conversation we precisely had on that topic. The church of the future needs to be a listening church, a dialogic church, and that was part of the positive and proactive dimension of that original document. In retrospect, it plays off with some of the ideas of Pope Paul VI in his document Ecclesiam Suam; that dialogue is a new way of being church, an idea which continues to be strongly reinforced by the Asian bishops in their recent documents.</p>
<p><b>In your book The Gospel in Cyberspace, you propose the imaginative metaphor of a &quot;kaleidoscopic catechesis&quot; to describe the dialogical approach.</b></p>
<p>I love kaleidoscopes, in fact, I have one here at the office. Kaleidoscopes are full of beauty, wonder and surprise. The content of a kaleidoscope is different kinds of shapes and colors of glass and each time you turn it, the colorful pieces fall into a different pattern. Yet there is something that is common to each pattern. They are the essential elements of kaleidoscope. The kaleidoscope refreshes my thinking that there is more than one way to do something. What we tend to do in our culture is that when we see a program, everybody just jumps into it, works it to death, and when it's finished, we ask &quot;who has the next program?&quot; That might be a good way to live for some people but a kaleidoscopic catechesis means that we educate people for seeing creative alternative possibilities in face of the ministry challenges we face every today. It calls for more diversity and plurality while holding onto those traditional realities that hold us together within community. We can be creative if we have the common elements ... we can say &quot;what if&quot; and &quot;why not,&quot; move to another chair, look at it from another angle and observe a new perspective.</p>
<p><b>From a media standpoint, wouldn't the rapidly-shifting technology define the pattern in a definitive way?</b></p>
<p>The technology may offer certain parameters for exploring possibilities, but there is always more than one methodology with any given technology. I have always believed that the church has not imagined enough the breadth and depth of media possibilities for communicating faith and positioning the gospel within our culture. It seems we do not take the required time nor invest the necessary resources to engage in this type of exploration. We do not fully realize the &quot;power of the media.&quot; We can truly make it work for the mission of the church.</p>
<p>The key element that holds this together isn't only the technology. The fundamental truths of our Catholic Christian heritage or story are precious to us. We need to consciously and creatively consider the different media resources available to us that can help amplify and animate that story. Consider how video, CD's, DVD's, cable TV, computers and the Internet can be techniques that offer us rich opportunities for communicating faith today. When you develop a kaleidoscopic mindset, you begin saying, &quot;Wow, there are many ways in which I can tell our faith story. I can learn to do this! I can learn new ways for communicating faith in an expanding communication age.&quot; We need to open ourselves to rich possibilities and don't get stuck in only one way.</p>
<p>Another thing about the kaleidoscope that ties right into our spirituality is that you really only see the beauty of the kaleidoscope when you turn it towards the light. It's in the light that you see the beauty of the pieces. For us, the light is God. And if we truly trust Jesus' words, &quot;I will be with you until the end of time,&quot; then we shouldn't be panicking. If we keep our vision focused, we can deal with diversity, richness, and plurality, because we have been grounded in clarity of sight (faith). It is only when we move away from the light that we do not see the beauty of all the diverse pieces. Furthermore, we miss seeing the possibility of new patterns of revelation that can emerge by shifting our position if only temporarily for new insight.</p>
<p><b>Angling this to the Virtual Learning Community of Faith Formation, isn't there a learning curve to negotiate when one gets into an online course?</b></p>
<p>That's a very important point. For some people, dealing with new technology could be a steep learning curve but that's only a temporary issue. They're people who didn't grow up with computers and the Internet and are reluctant about any new technology especially linked to adult faith formation. But the more time they spend with computers and the Internet they become comfortable with it. They learn to easily navigate through the new methodology for adult learning and even begin to see additional possibilities for expanding their online experiences. This would be the first learning curve. The second learning curve has to do with how you guide adult learners to critically read, reflect and communicate (write) online. These are required skills for effective online learning. This is definitely different than our traditional learning environments. In a traditional environment it is possible that the students or participants may not have to be accountable to read, reflect and communicate back what they have heard or learned. Yet, how do we really know that someone has understood what we are striving to communicate unless it can be verified in some form. Physical presence in a room is no guarantee of learning. However, if an online learning experience is to be successful students or participants must practice and develop these skills over time.</p>
<p>We have only unveiled the tip of the iceberg for the future of online learning for adult faith formation. There are methodologies that still need to be explored and developed. As our adult Virtual Learning Community students and facilitators advance in their skills, our [formation team] team, which is carefully observing the ongoing process, are exploring new online paradigms for learning. We continuously design and revise our templates based on the changing profiles and experiences of our students. Yes, this takes a lot of time, personnel and resources but we are committed to the ongoing process. The kaleidoscope concept is critical here. The Institute for Pastoral Initiatives perceives our mission to engage in ongoing research and development of new online methodologies that can support the future of adult faith formation.</p>
<p><b>What are the kaleidoscopic patterns you see at this stage of your commitment to media literacy?</b></p>
<p>The Media culture is changing every day. While we do not have to be involved with every aspect of the culture, we need to make our specific contribution. The church needs pioneers in these changing times. Pioneers who can remain positive and proactive in exploring possibilities. We need to find a new way of being church within the expanding cyber culture. With or without us this culture is mushrooming as we are now speaking. If the church is not well defined within the culture, the church within this culture can be irrelevant. You ask about my commitment now? Well, we are going to gamble high and wide continuing to explore alternative possibilities for adult faith formation online. Over 30 years ago I began with cable television. I saw the possibilities of cable amidst naysayers concerning its future. Well, here we are and cable is woven into the fabric of our culture. The church's view of the Internet is a little more than the church's vision was of cable in the '70s. However, I'm not giving up. I've learned a lot; we've learned a lot, and we're going to take it to a new place the next time around. That's where I get a lot of my energy and creativity. I know it is a &quot;cinch by the inch and hard by the yard.&quot; We are going inch by inch but we are moving fast.</p>
<p class="center"><i>National Catholic Reporter: Global Perspective</i><br><?php print vlc_external_link('http://www.nationalcatholicreporter.org/globalpers/gp092104.htm', 'http://www.nationalcatholicreporter.org/globalpers/gp092104.htm') ?><br>September 21, 2004</p>
<!-- end page content -->
<?php
$footer = vlc_footer($site_info, $page_info, $user_info, $lang);
print $footer;
?>

