<?php
$page_info['section'] = 'news';
$page_info['page'] = 'article';
$page_info['login_required'] = 0;
list($user_info, $lang, $status_message, $header) = vlc_header($site_info, $page_info);
print $header;
?>
<!-- begin page content -->
<p class="center"><b>The Founders of the Marianist Family: Their Lives and Times - An On-line Course</b></p>
<p class="center">by Carol Ramey</p>
<p>Imagine -- it's 10:30 p.m. on a Tuesday evening. You have read the assignment for the week. Now you are going to go to class to answer the instructor's questions and discuss key points from the readings with the other students. Going to class late in the evening? Yes, or early in the morning, or over lunch, or, if you want, in the middle of the night. You are participating in a virtual learning community in cyberspace.</p>
<p>The North American Center for Marianist Studies (NACMS) will soon launch the first internet-based course on the history of the Marianist founders. Through a partnership with the Institute for Pastoral Initiatives (IPI) at the University of Dayton, we are working with Sister Angela Ann Zukowski, MHSH, D.Min. and her staff at the IPI to develop the course. All the elements of a regular academic class have been loaded into a site on the internet - a pre-test, required readings, questions for class discussion, statements upon which to reflect and draw new understanding or practical application, and, of course, a test at the end of each segment of the course. Students will learn about the lives and times of Father William Joseph Chaminade, Adele de Batz de Trenquelleon, and Marie-Therese de Lamourous.</p>
<p>This may sound like a correspondence course using electronic media. It is more! I had seen a demonstration of the technology, but really became excited about it after I became a student in a cyber-class - more on my personal experience later. The new instructional method is adapted to the times - something Father Chaminade urged Marianists to do when he spoke of &quot;New Wars.&quot;</p>
<p>By using message boards and e-mails, students stay in regular contact with the instructor and each other. There is even a place on the site to post photos and short biographies, so the students get to know each other. Through the interactions during the five weeks of the course, students come to know and predict who among the class will be the intellectual, who will be the pragmatist, who will add humor to the discussions, who will ask the hard question that even makes the instructor stop and think. It is a learning community.</p>
<p>The advantages of such a course are many. Students and instructors can participate from anywhere on the globe where Internet access is possible. Class goes on despite weather, remote living situations, varied schedules - even illness or travel. The isolation many people experience through typical at-distance programs is overcome. If you can get to a computer, you can be in class.</p>
<p>Originally conceived and still expanding to assist diocesan personnel train catechetical leaders who live at distance from traditional educational institutions, the course templates designed by IPI have been used by NACMS to open up Marianist studies to those who cannot travel or commit to a specific timeframe for standard instructional opportunities.</p>
<p>NACMS plans to add more courses on Marianist studies - spirituality and history - and more instructors when possible. The classes are limited to 12 participants, so interaction between student and instructor and among classmates is manageable. The classes last five weeks. Continuing education credits will be available through the University of Dayton.</p>
<p>To prepare for acting as a class facilitator, I took a class through UD's Virutual Learning Community. I studied &quot;Media, Faith, and Values&quot; under the guidance of Sister Angela Ann. Not only did I come away with new insight into the role of media in value and faith formation, I also came to know some wonderful people who take their spiritual journey very seriously and who are looking for ways to develop their own faith lives and those of their students. To computer-assisted learning, the Virutal Learning Community provides a relational component - a value that is held highly by Marianists.</p>
<p>This was no shortcut to learning. It took discipline to log on every day. I had to make a shift from thinking I was just fulfilling course requirements with the reading and the answering of questions. I found the class spirit growing as we students read each other's remarks, posted responses or reactions, and kept up with the dialogue. As the weeks progressed, I was disappointed if I logged on and found no new postings. At the beginning of the course I would say to myself, &quot;I should log-on.&quot; At some point in the middle of the second week it shifted to, &quot;I want to log-on.&quot;</p>
<p>The new venture has long been a dream at NACMS. Our primary mandate falls within the Marianist Office of Instruction - we are charged with providing programs, publications, research, and resources on a myriad of tipics related to Marianist studies. With lay groups developing in so many places, members are asking for resources and background on Marianist life - the stories of the early foundations, the special characteristics of the spirituality, and practical ways communities can form and be sustained. NACMS has a wide array of resources for the comprehensive Marianist Family, but geography and life commitments often limit ways people can access our offerings. Also, the classes can be &quot;attended&quot; internationally by Marianist religious in formation or renewal programs.</p>
<p>The registration date and process will be announced soon through a news release and on the <?php print vlc_external_link('nacms.org', 'http://www.nacms.org/') ?> website. Maybe we'll meet soon - virtually.</p>
<!-- end page content -->
<?php
$footer = vlc_footer($site_info, $page_info, $user_info, $lang);
print $footer;
?>

