<?php
$page_info['section'] = 'news';
$page_info['page'] = 'article';
$page_info['login_required'] = 0;
list($user_info, $lang, $status_message, $header) = vlc_header($site_info, $page_info);
print $header;
?>
<!-- begin page content -->
<p class="center"><b>ADULT EDUCATION IN CATHOLIC FAITH</b></p>
<p>(Dayton, OH) -- With busy lives and limited time, many Catholic adults put faith formation at the bottom of their to-do lists.</p>
<p>But the Institute for Pastoral Initiatives has partnered with the University of Dayton to make courses in Catholic topics available online. Participants need a computer, Internet connection and e-mail to study topics in church history, sacraments, ecclesiology, evangelization and Scripture.</p>
<p>The Virtual Learning Community in Faith Formation (<?php print vlc_external_link('http://www.udayton.edu/', 'http://www.udayton.edu/') ?>), is organized and operated by the Institute of Pastoral Initiatives of the University of Dayton. Eighteen partner dioceses and the North American Center for Marianist Studies promote the courses to teachers, catechists and other adults who are interested in furthering their faith education.</p>
<p>The courses are open to all. Cost is $40 for members of partner dioceses and $75 for those outside the network.</p>
<p>&quot;It has been a joy for me to see the response of the class to one another and to me,&quot; said the Rev. Anthony G. Bosco, bishop of the Diocese of Greensburg, Pa., and facilitator of a course on &quot;Images of Jesus, A study in Christology.&quot; &quot;It is the cutting edge for adult faith formation, which is a real challenge for us today. Because it can be done at the student’s convenience, it is ideal for busy people who wish to grow in the faith. It is also very user friendly.</p>
<p>&quot;If Christ were on earth today, he would certainly use the most effective means of communicating. But shame on me. He is alive and with us today. He is using us and our computers to evangelize.&quot;</p>
<p>VLCFF currently offers eight courses, three sections per course six times a year, ranging from &quot;Mary in Scripture and Tradition&quot; to &quot;Media, Faith and Values.&quot; Each of the courses, which run for five weeks, is updated with fresh material every 18 to 24 months, and 10 additional courses are in development.</p>
<p>&quot;For my specific area, media education, this is a whole new way to create awareness about media, faith, values and culture for parents, teachers or whomever takes the classes,&quot; said Sister Rose Pacatte, FSP, director of the Pauline Center for Media Studies in Culver City, Calif., and one of 42 VLCFF facilitators located across the country. &quot;The discipline can now arrive at the homes or workplaces of people who seriously want to develop their faith learning, and across miles we can enter into dialogue about what matters most to us.&quot;</p>
<p>Classes are kept small, with enrollment capped at 12 to preserve interaction between facilitators and participants. Students generally spend about 25 hours during the five weeks reading, writing reflections and exchanging ideas by posting on the course discussion board.</p>
<p>Participant’s reflections upon completing a course are affirming. &quot;I enjoyed being able to work on the course at my convenience and from home. &quot;  &quot;I was skeptical at first but found the online course to be a great way to connect people from across the country.  We were able to share ideas and personal stories and become a true &quot;class&quot;.  &quot;I’m not sure I would have been willing to express some of my doubts in a traditional classroom setting.&quot; &quot;Because of our isolated location, we don’t have much in the way of adult religious formation courses.  We have one weeklong catechetical institute each year but that is it.  Now we have it whenever we need it.  It’s great.&quot;</p>
<p>It’s a program that complements the educational programs offered in our parishes.  The courses can be applied toward our diocesan certification process.  Each course completed is recognized with a certificate with our diocesan name and signed by  a representative from the diocese.</p>
<p>Persons participating in the courses are adults interested in learning more about their faith, catechists, Catholic School teachers, members of RCIA programs and others working toward lay leadership formation.</p>
<p>&quot;Despite our emphasis in this country on parish programs for children, Christianity is a religion for adults,&quot; said Carol Ann Cannon, facilitator and course designer for VLCFF. &quot;So a parent’s understanding of faith may come from when they had classes as children, and many adults seldom move beyond that point. But when parents are involved in some form of education for themselves, so much more is passed on to children, especially the idea that learning is a lifelong process.&quot;</p>
<p>&quot;The financial situation of dioceses is of concern to us all,&quot; Sr. Angela Ann Zukowski said. &quot;Many are cutting back on religious education or ministry budgets. In one sense, this is why dioceses partner with us, it is our goal to compliment and support diocesan efforts in service and outreach in adult faith and catechist formation.&quot;</p>
<p>The Institute plans to pilot a three-week seminar this summer for those who can’t commit to even a five-week schedule. The first will focus on the church document on adult faith formation, &quot;Our Hearts Were Burning Within Us.&quot; Later seminars will focus on other church documents, social justice and emerging pastoral needs and issues of the Church.</p>
<p>&quot;The classes help me grow in my own faith because the students’ lives and insights are so full, rich and faith-filled,&quot; Pacatte said. &quot;I am so inspired. The students take the time, put in so much effort and really engage. What a witness to how much their faith means to them.&quot;</p>
<p>&quot;The Catholic Church&quot;, says Zukowski, &quot;cannot ignore the impact or value that the Internet is offering world cultures.  If the Catholic Church is to take catechesis, evangelization and adult faith formation seriously, we must be where a growing number of Catholics and others searching for God (faith) are to be found.  That is – cyberspace.&quot;</p>
<p>For media interviews, contact the Rev. Anthony Bosco at (724) 837-0901 or <?php print vlc_mailto_link('abosco@dioceseofgreensburg.org', 'abosco@dioceseofgreensburg.org', 'VLCFF') ?>; Sister Rose Pacatte, FSP, at (310) 636-8385 or <?php print vlc_mailto_link('RosePacatte@pauline.org', 'RosePacatte@pauline.org', 'VLCFF') ?>; Carol Ann Cannon at (937) 429-3235 or <?php print vlc_mailto_link('cacannon@coax.net', 'cacannon@coax.net', 'VLCFF') ?>; and Sister Angela Ann Zukowski, MHSH, D.Min., at (937) 229-3126 or <?php print vlc_mailto_link('Angela.Zukowski@notes.udayton.edu', 'Angela.Zukowski@notes.udayton.edu', 'VLCFF') ?>.</p>
<!-- end page content -->
<?php
$footer = vlc_footer($site_info, $page_info, $user_info, $lang);
print $footer;
?>

